# Generated by Django 5.2.10 on 2026-09-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0014_student_major_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('program', 'code')},
        ),
    ]
