# Generated by Django 5.2.10 on 2026-09-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0017_canonical_program_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_number', 'No student number in the file'), ('shared_number', 'Student number shared with another student'), ('duplicate_row', 'Student listed twice in the file'), ('unreadable_row', 'Row could not be read'), ('generated_number', 'Imported with a generated student number')], max_length=20)),
                ('name', models.CharField(blank=True, default='', help_text='Student name as printed in the file', max_length=100)),
                ('student_id', models.CharField(blank=True, default='', help_text='Number as printed in the file, or the generated one', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='', help_text='Why this row needs attention')),
                ('source_file', models.CharField(blank=True, default='', help_text='File the row came from', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_issues', to='qrapp.program')),
            ],
            options={
                'verbose_name': 'Import issue',
                'verbose_name_plural': 'Import issues',
                'ordering': ['issue_type', 'name', 'student_id'],
            },
        ),
    ]
