# Generated by Django 5.2.10 on 2026-09-19 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0020_attendance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date.today, help_text='Day this event happens on. date.today (not timezone.localdate) because Django 5.x localdate() raises ValueError when USE_TZ=False.'),
        ),
    ]
