"""
Django settings for qrproject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").strip().lower() in ("1", "true", "yes", "on")

_allowed_hosts = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,192.168.48.1",
)

ALLOWED_HOSTS = [
    host.strip()
    for host in _allowed_hosts.split(",")
    if host.strip()
]

if os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(os.getenv("RENDER_EXTERNAL_HOSTNAME"))

_csrf_trusted = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "",
)
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in _csrf_trusted.split(",")
    if o.strip()
]

if os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{os.getenv('RENDER_EXTERNAL_HOSTNAME')}"
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qrapp'
]

# Dev-only HTTPS server (runserver_plus) so phone cameras work on the LAN —
# getUserMedia requires a secure context (HTTPS or localhost).
if os.getenv("ENABLE_HTTPS_DEV", "").strip().lower() in ("1", "true", "yes", "on"):
    try:
        import django_extensions  # noqa: F401
        INSTALLED_APPS.append("django_extensions")
    except ImportError:
        pass

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

USE_CLOUDINARY = all(
    (CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET)
)

if USE_CLOUDINARY:
    INSTALLED_APPS += [
        "cloudinary_storage",
        "cloudinary",
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
]

# ---------------- CACHING ----------------
# Shared cache when REDIS_URL is provided (recommended in production, e.g. a
# Render Key Value instance); otherwise falls back to per-process local
# memory, which is fine for local development.
REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    _CACHE_BACKEND = "django.core.cache.backends.redis.RedisCache"
    _CACHE_LOCATION = REDIS_URL
else:
    _CACHE_BACKEND = "django.core.cache.backends.locmem.LocMemCache"
    _CACHE_LOCATION = "qrapp-local"

CACHES = {
    "default": {
        "BACKEND": _CACHE_BACKEND,
        "LOCATION": _CACHE_LOCATION,
        "KEY_PREFIX": "qr",
        "TIMEOUT": 300,
    },
    # Dedicated, never-expiring cache for rate-limit counters so they don't
    # compete with (or get evicted by) regular cached data.
    "ratelimit": {
        "BACKEND": _CACHE_BACKEND,
        "LOCATION": _CACHE_LOCATION,
        "KEY_PREFIX": "qr-rl",
        "TIMEOUT": None,
    },
    # Short-lived cache for lookup AJAX endpoints (colleges/programs/majors/events).
    "lookups": {
        "BACKEND": _CACHE_BACKEND,
        "LOCATION": _CACHE_LOCATION,
        "KEY_PREFIX": "qr-lookups",
        "TIMEOUT": 300,
    },
}

# ---------------- RATE LIMITING (django-ratelimit) ----------------
RATELIMIT_USE_CACHE = "ratelimit"
RATELIMIT_VIEW = "qrapp.views.ratelimited_view"
RATELIMIT_ENABLE = os.getenv("RATELIMIT_ENABLE", "True").strip().lower() in ("1", "true", "yes", "on")
# Keep the app available if the cache backend hiccups: allow the request
# instead of rejecting everyone while the cache is down.
RATELIMIT_FAIL_OPEN = True

# Behind proxies/load balancers (e.g. Render), set RATELIMIT_IP_META_KEY in the
# environment (typically "HTTP_X_FORWARDED_FOR") so per-IP limits see the real
# client IP instead of the proxy IP.
_rate_ip_meta_key = os.getenv("RATELIMIT_IP_META_KEY", "")
if _rate_ip_meta_key:
    RATELIMIT_IP_META_KEY = _rate_ip_meta_key

# Cache lifetimes (seconds), tunable via environment
CALENDAR_CACHE_TIMEOUT = int(os.getenv("CALENDAR_CACHE_TIMEOUT", "60"))
LOOKUPS_CACHE_TIMEOUT = int(os.getenv("LOOKUPS_CACHE_TIMEOUT", "60"))

ROOT_URLCONF = 'qrproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qrproject.wsgi.application'


# Database

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Render PostgreSQL
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }

else:
    # Local development
    DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

    if DB_ENGINE == "mysql":
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": os.getenv("DB_NAME", "qrproject"),
                "USER": os.getenv("DB_USER", "root"),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "HOST": os.getenv("DB_HOST", "127.0.0.1"),
                "PORT": os.getenv("DB_PORT", "3306"),
                "OPTIONS": {
                    "charset": "utf8mb4",
                    "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                },
            }
        }

        # XAMPP/MariaDB compatibility
        from django.db.backends.mysql.features import DatabaseFeatures

        @property
        def _xampp_minimum_database_version(self):
            if self.connection.mysql_is_mariadb:
                return (10, 4)
            return (8, 0, 11)

        @property
        def _xampp_can_return_columns_from_insert(self):
            if self.connection.mysql_is_mariadb:
                return self.connection.mysql_version >= (10, 5)
            return self.connection.mysql_version >= (8, 0, 19)

        DatabaseFeatures.minimum_database_version = (
            _xampp_minimum_database_version
        )

        DatabaseFeatures.can_return_columns_from_insert = (
            _xampp_can_return_columns_from_insert
        )

    else:
        # Local SQLite
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / os.getenv(
                    "SQLITE_NAME",
                    "db.sqlite3",
                ),
            }
        }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True
USE_TZ = False

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'admin_dashboard'   # after login → main dashboard
LOGOUT_REDIRECT_URL = 'login'    # after logout → back to login



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'qrapp/static'),
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
    }
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# QR security: new QR codes are signed. Set True only after regenerating all printed QRs.
QR_REQUIRE_SIGNATURE = os.getenv("QR_REQUIRE_SIGNATURE", "False").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
